#!/usr/bin/env python3
"""
Guida per estrarre cookies Facebook per lo scraping autenticato
"""

print("🍪 GUIDA: Come ottenere i cookies di Facebook")
print("=" * 60)
print()
print("📋 METODO 1 - Da Browser (Chrome/Firefox):")
print("1. Apri Facebook.com e fai login")
print("2. Premi F12 per aprire Developer Tools")
print("3. Vai al tab 'Application' (Chrome) o 'Storage' (Firefox)")
print("4. Nella sidebar sinistra: Storage > Cookies > https://www.facebook.com")
print("5. Cerca questi cookies ESSENZIALI:")
print("   - c_user")
print("   - xs") 
print("   - sb")
print("   - datr")
print("6. Copia nome=valore per ognuno")
print()
print("📋 METODO 2 - Export cookies (più semplice):")
print("1. Installa estensione browser 'Get cookies.txt LOCALLY'")
print("2. Vai su facebook.com (loggato)")
print("3. Clicca sull'estensione e scarica cookies.txt")
print()
print("🔐 SICUREZZA:")
print("- I cookies sono personali e sensibili")
print("- Non condividerli mai")
print("- Hanno scadenza limitata")
print("- Se cambi password Facebook, dovrai aggiornarli")
print()
print("📁 DOVE SALVARE:")
print("- config/facebook_cookies.txt (formato Netscape)")
print("- O config/facebook_cookies.json (formato JSON)")
print()
print("▶️  Dopo aver ottenuto i cookies, esegui:")
print("   python3 facebook_scraper_donnefuori.py")